-- LESSON 3 - Step 2: Validate rows
-- 
-- To validate rows, we can use SQL queries to check for 
-- specific conditions or patterns in the data. In this case,
-- we are checking that the subscription_tier column only contains
-- the values 'free' and 'paid'.
--
-- Uncomment the following query, and run the pipeline again.
-- 
-- SELECT 
--     'incorrect tier' as message, subscription_tier
-- FROM 
--     raw_subscriptions
-- WHERE
--     subscription_tier NOT IN ['free', 'paid']
-- LIMIT 10;